#!/usr/bin/env python3

# Check that the make command don't execute any rules and had an unexpected error

import sys
import os
import subprocess

p = subprocess.Popen(["make"] + sys.argv[1:], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
try:
    p.wait(20)
except subprocess.TimeoutExpired:
    print("The second make run takes too long, probably a task is running again")
    sys.stdout.flush()
    p.kill()
    print("Rerun in debug mode")
    sys.stdout.flush()
    os.environ["DEBUG"] = "TRUE"
    subprocess.call(["make"] + sys.argv[1:], env=os.environ)
    exit(2)
if p.returncode != 0:
    print("make call error:")
    subprocess.call(["make"] + sys.argv[1:])
exit(p.returncode)
